---
title: "First Pass Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
rm(list = ls())
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(nnet)
library(devtools)
library(countrycode)
library(Amelia)
library(expss)
library(kableExtra)
library(knitr)
library(mlogit)
library(MASS)
library(foreign)
library(stargazer)
library(lmtest)
library(arm)
library(Hmisc)
library(corrplot)
library(AER)
library(cowplot)
library(PerformanceAnalytics)
library(Zelig)
library(car)
library(lmtest)
library(psych)
library(magicfor)
library(foreach)
library(iterators)
```

#Botswana
```{r}
#Load Botswana
data <- read.csv("botswana_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- chisq.test(famresults[1:2,1:2], correct = FALSE)$p.value
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

botresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
botchi <- as.data.frame(cbind(genchi,famchi))
colnames(botchi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(botchi) <- c(1: nrow(botchi))

botchi <- as.data.frame(cbind(comparison,botchi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi")))

botchi$country <- c("Botswana")
botresults$country <- c("Botswana")
```

#Nepal
```{r}
#Load Nepal
data <- read.csv("nepal_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(weight) %>%
        sum()
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- chisq.test(famresults[1:2,1:2], correct = FALSE)$p.value
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

nepalresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
nepalchi <- as.data.frame(cbind(genchi,famchi))
colnames(nepalchi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(nepalchi) <- c(1: nrow(nepalchi))

nepalchi <- as.data.frame(cbind(comparison,nepalchi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi")))

nepalchi$country <- c("Nepal")
nepalresults$country <- c("Nepal")
```

#Swaziland
```{r}
#Load Swaziland
data <- read.csv("swazi_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- chisq.test(famresults[1:2,1:2], correct = FALSE)$p.value
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

swaziresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
swazichi <- as.data.frame(cbind(genchi,famchi))
colnames(swazichi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(swazichi) <- c(1: nrow(swazichi))

swazichi <- as.data.frame(cbind(comparison,swazichi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi","swaziresults","swazichi")))

swazichi$country <- c("Swaziland")
swaziresults$country <- c("Swaziland")
```

#Lesotho
```{r}
#Load Lesotho
data <- read.csv("lesotho_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- chisq.test(famresults[1:2,1:2], correct = FALSE)$p.value
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

lesresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
leschi <- as.data.frame(cbind(genchi,famchi))
colnames(leschi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(leschi) <- c(1: nrow(leschi))

leschi <- as.data.frame(cbind(comparison,leschi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi","swaziresults","swazichi","leschi","lesresults")))

leschi$country <- c("Lesotho")
lesresults$country <- c("Lesotho")
```

#Mozambique
```{r}
#Load Mozambique
data <- read.csv("mozambique_master2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- "NA"
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

mozresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
mozchi <- as.data.frame(cbind(genchi,famchi))
colnames(mozchi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(mozchi) <- c(1: nrow(mozchi))

mozchi <- as.data.frame(cbind(comparison,mozchi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi","swaziresults","swazichi","leschi","lesresults","mozresults","mozchi")))

mozchi$country <- c("Mozambique")
mozresults$country <- c("Mozambique")
```

#Zambia
```{r}
#Load Zambia
data <- read.csv("zambia_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- "NA"
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

zamresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
zamchi <- as.data.frame(cbind(genchi,famchi))
colnames(zamchi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(zamchi) <- c(1: nrow(zamchi))

zamchi <- as.data.frame(cbind(comparison,zamchi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi","swaziresults","swazichi","leschi","lesresults","mozresults","mozchi","zamresults","zamchi")))

zamchi$country <- c("Zambia")
zamresults$country <- c("Zambia")
```

#Malawi
```{r}
#Load Malawi
data <- read.csv("malawi_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z, column) {
  data%>%
        filter(disflag == x & sexflag == y & data[,column] == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination for general violence
genresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "genvioflag")
}

genresults <- as.data.frame(cbind(genresults[1:2,1],genresults[3:4,1]))
colnames(genresults) <- c("gno_vio","gvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(genresults$gno_vio),sum(genresults$gvio))

genresults <- rbind(genresults,total)

rm(i,j,z,total)

#Generate percentages
genresults$gnvpercent <- genresults$gno_vio/sum_row(genresults$gno_vio,genresults$gvio)
genresults$gvpercent <- genresults$gvio/sum_row(genresults$gno_vio,genresults$gvio)

#Repeat Process for family violence
famresults <- foreach(i = rep(1,4), j = rep(c(0,1),2), z = c(0,0,1,1), .combine = 'rbind')%do% {
  count_matches(i,j,z, column = "famvioflag")
}

famresults <- as.data.frame(cbind(famresults[1:2,1],famresults[3:4,1]))
colnames(famresults) <- c("fno_vio","fvio")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(famresults$fno_vio),sum(famresults$fvio))

famresults <- rbind(famresults,total)

rm(i,j,z,total)

#Generate percentages
famresults$fnvpercent <- famresults$fno_vio/sum_row(famresults$fno_vio,famresults$fvio)
famresults$fvpercent <- famresults$fvio/sum_row(famresults$fno_vio,famresults$fvio)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder, first general
gnvci <- foreach(i = genresults[,"gnvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gnvci) <- c("gnvlower95", "gnvupper95")

gvci <- foreach(i = genresults[,"gvpercent"], j = rep(1.96, nrow(genresults)), k = rowSums(genresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(gvci) <- c("gvlower95", "gvupper95")

genresults <- cbind(genresults,gnvci,gvci)

genresults <- genresults[c(1:2,5,3,6,7,4,8)]

#Now for family violence
fnvci <- foreach(i = famresults[,"fnvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fnvci) <- c("fnvlower95", "fnvupper95")

fvci <- foreach(i = famresults[,"fvpercent"], j = rep(1.96, nrow(famresults)), k = rowSums(famresults[,1:2]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(fvci) <- c("fvlower95", "fvupper95")

famresults <- cbind(famresults,fnvci,fvci)

famresults <- famresults[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women General Violence

genchi <- chisq.test(genresults[1:2,1:2], correct = FALSE)$p.value

famchi <- "NA"
```

```{r}
#Combine the two datasets and chi tests

results <- cbind(genresults,famresults)

#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$gengrouptot <- rowSums(results[,c("gno_vio","gvio")])

results$famgrouptot <- rowSums(results[,c("fno_vio","fvio")])

results <- results[c(17:18,1:8,19,9:16)]

malresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
malchi <- as.data.frame(cbind(genchi,famchi))
colnames(malchi) <- c("gen_pval","fam_pval")
comparison <- c("mwD vs wwD")
rownames(malchi) <- c(1: nrow(malchi))

malchi <- as.data.frame(cbind(comparison,malchi))

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi","swaziresults","swazichi","leschi","lesresults","mozresults","mozchi","zamresults","zamchi","malresults","malchi")))

malchi$country <- c("Malawi")
malresults$country <- c("Malawi")
```

#Plots
```{r}
#Combine the 3 Data Sets

totalresults <- rbind(botresults, nepalresults, swaziresults, lesresults, mozresults, zamresults, malresults)

totalresults <- totalresults[c(20,1:19)]

rownames(totalresults) <- c(1:nrow(totalresults))

write.table(totalresults, file = "vio_analysis.csv", sep = ",", row.names = F)

#Combine the 3 Chi Sets

totalchi <- rbind(botchi,nepalchi, swazichi, leschi, mozchi, zamchi, malchi)

totalchi <- totalchi[c(4,1:3)]

rownames(totalchi) <- c(1:nrow(totalchi))

write.table(totalchi, file = "vio_chi.csv", sep = ",", row.names = F)
```

```{r}
#Plot the results

totalresults$group <- as.factor(totalresults$group)

print(levels(totalresults$group))

totalresults$group <- factor(totalresults$group, levels(totalresults$group)[c(1,3,2)])

ggplot(data = totalresults, aes(x = group, y = gvpercent, group = country)) +
  geom_point(aes(color = country)) +
  geom_errorbar(ymin = totalresults$gvlower95, ymax = totalresults$gvupper95)+
  labs(title = "Rate of Self Reported\n Poor Total Health by Group", x = "Groupings of Individuals", y = "Percent Reporting\n Poor Health", color = "Country") +
  coord_cartesian(ylim = c(0,.6)) +
  scale_y_continuous(breaks = seq(0,.6,.1), labels = scales::percent)
```

```{r}
#Bubble Plot
gvgendergap <- foreach (k = which(totalresults$group == "mwd"), j = which(totalresults$group == "wwd"), .combine = "rbind") %do% {
  totalresults[j, "gvpercent"] - totalresults[k, "gvpercent"]
}

#bubble <- cbind(bubble, gendergap)

#b <- ggplot(bubble, aes(x = country, y = gpercent, group = group)) +
#  geom_jitter(position = position_dodge(width = 0),aes(color = group, size = gendergap)) +
#  geom_errorbar(ymin = bubble$glower95, ymax = bubble$gupper95) +
#  labs(title = "Rate of Self Reported\n Good Total Health by Group", x = "Country", y = "Percent #Reporting\n Good Health", color = "Persons Group", size = "Gender Gap") +
#  coord_cartesian(ylim = c(0,1)) +
#  scale_y_continuous(breaks = seq(0,1,.1), labels = scales::percent)
  
#b
```