---
title: "First Pass Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
rm(list = ls())
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(nnet)
library(devtools)
library(countrycode)
library(Amelia)
library(expss)
library(kableExtra)
library(knitr)
library(mlogit)
library(MASS)
library(foreign)
library(stargazer)
library(lmtest)
library(arm)
library(Hmisc)
library(corrplot)
library(AER)
library(cowplot)
library(PerformanceAnalytics)
library(Zelig)
library(car)
library(lmtest)
library(psych)
library(magicfor)
library(foreach)
library(iterators)
```

#Botswana
```{r}
#Load Botswana
data <- read.csv("botswana_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

botresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
botchi <- as.data.frame(totalchi)
colnames(botchi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(botchi) <- c(1: nrow(botchi))

botchi <- as.data.frame(cbind(botchi,comparison))
botchi <- botchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi")))

botchi$country <- c("Botswana")
botresults$country <- c("Botswana")
```

#Nepal
```{r}
#Load Nepal
data <- read.csv("nepal_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(weight) %>%
        sum()
}

#Record observations of each combination
#Because none available is unobserved for nepal, to make the formula work, rep "1" 4 times in "z"
#for the toiletflag. this allows the formula to run, but this extraneous data needs to be discarded
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(1,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

#discarded extraneous run here
results <- as.data.frame(cbind(results[1:2,1],c(0,0),results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

nepalresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
nepalchi <- as.data.frame(totalchi)
colnames(nepalchi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(nepalchi) <- c(1: nrow(nepalchi))

nepalchi <- as.data.frame(cbind(nepalchi,comparison))
nepalchi <- nepalchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi")))

nepalchi$country <- c("Nepal")
nepalresults$country <- c("Nepal")
```

#Swaziland
```{r}
#Load Swaziland
data <- read.csv("swazi_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

swaziresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
swazichi <- as.data.frame(totalchi)
colnames(swazichi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(swazichi) <- c(1: nrow(swazichi))

swazichi <- as.data.frame(cbind(swazichi,comparison))
swazichi <- swazichi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults")))

swazichi$country <- c("Swaziland")
swaziresults$country <- c("Swaziland")
```

#Lesotho
```{r}
#Load Lesotho
data <- read.csv("lesotho_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

lesresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
leschi <- as.data.frame(totalchi)
colnames(leschi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(leschi) <- c(1: nrow(leschi))

leschi <- as.data.frame(cbind(leschi,comparison))
leschi <- leschi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults", "lesresults","leschi")))

leschi$country <- c("Lesotho")
lesresults$country <- c("Lesotho")
```

#Mozambique
```{r}
#Load Mozambique
data <- read.csv("mozambique_master2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

mozresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
mozchi <- as.data.frame(totalchi)
colnames(mozchi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(mozchi) <- c(1: nrow(mozchi))

mozchi <- as.data.frame(cbind(mozchi,comparison))
mozchi <- mozchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults", "lesresults","leschi", "mozchi", "mozresults")))

mozchi$country <- c("Mozambique")
mozresults$country <- c("Mozambique")
```

#Zambia
```{r}
#Load Zambia
data <- read.csv("zambia_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

zamresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
zamchi <- as.data.frame(totalchi)
colnames(zamchi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(zamchi) <- c(1: nrow(zamchi))

zamchi <- as.data.frame(cbind(zamchi,comparison))
zamchi <- zamchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults", "lesresults","leschi", "mozchi", "mozresults", "zamresults", "zamchi")))

zamchi$country <- c("Zambia")
zamresults$country <- c("Zambia")
```

#Malawi
```{r}
#Load Malawi
data <- read.csv("malawi_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & toiletflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1),3), j = rep(c(0,1),3), z = c(rep(1,2),rep(2,2),rep(0,2)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:2,1],results[3:4,1],results[5:6,1]))
colnames(results) <- c("toilet","none","naccess")

#Total and subtotal individuals w & w/o disabilities
total <- c(sum(results$toilet),sum(results$none),sum(results$naccess))

results <- rbind(results, total)

rm(i,j,z, total)

#Generate percentages
results$tpercent <- results$toilet/sum_row(results$toilet,results$naccess,results$none)
results$npercent <- results$none/sum_row(results$toilet,results$naccess,results$none)
results$napercent <- results$naccess/sum_row(results$toilet,results$naccess,results$none)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder
nci <- foreach(i = results[,"npercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nci) <- c("nlower95", "nupper95")

naci <- foreach(i = results[,"napercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(naci) <- c("nalower95", "naupper95")

tci <- foreach(i = results[,"tpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(tci) <- c("tlower95", "tupper95")

results <- cbind(results,tci,nci,naci)

results <- results[c(1:3,7,4,8,9,5,10,11,6,12)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Men vs Women
totalchi <- chisq.test(results[1:2,c(1,3)], correct = FALSE)$p.value

```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","total")

results$grouptot <- rowSums(results[,1:3])

results <- results[c(13:14,1:12)]

malresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
malchi <- as.data.frame(totalchi)
colnames(malchi) <- c("P-Values")
comparison <- c("mwD vs wwD")
rownames(malchi) <- c(1: nrow(malchi))

malchi <- as.data.frame(cbind(malchi,comparison))
malchi <- malchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults", "lesresults","leschi", "mozchi", "mozresults", "zamresults", "zamchi","malresults","malchi")))

malchi$country <- c("Malawi")
malresults$country <- c("Malawi")
```

#Plots
```{r}
#Combine the 3 Data Sets

totalresults <- rbind(botresults, nepalresults, swaziresults, lesresults, mozresults, zamresults)

totalresults <- totalresults[c(15,1:14)]

rownames(totalresults) <- c(1:nrow(totalresults))

write.table(totalresults, file = "toilet_analysis.csv", sep = ",", row.names = F)

#Combine the 3 Chi Sets

totalchi <- rbind(botchi, nepalchi, swazichi, leschi, mozchi, zamchi)

totalchi <- totalchi[c(3,1,2)]

rownames(totalchi) <- c(1:nrow(totalchi))

write.table(totalchi, file = "toilet_chi.csv", sep = ",", row.names = F)
```

```{r}
#Plot the results

totalresults$group <- as.factor(totalresults$group)

print(levels(totalresults$group))

totalresults$group <- factor(totalresults$group, levels(totalresults$group)[c(3,6,4,7,1,2,5)])

ggplot(data = totalresults, aes(x = group, y = napercent, group = country)) +
  geom_point(aes(color = country)) +
  geom_errorbar(ymin = totalresults$nalower95, ymax = totalresults$naupper95)+
  labs(title = "Rate of Self Reported\n Poor Total Health by Group", x = "Groupings of Individuals", y = "Percent Reporting\n Poor Health", color = "Country") +
  coord_cartesian(ylim = c(0,.4)) +
  scale_y_continuous(breaks = seq(0,.4,.05), labels = scales::percent)
```