---
title: "First Pass Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
rm(list = ls())
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(nnet)
library(devtools)
library(countrycode)
library(Amelia)
library(expss)
library(kableExtra)
library(knitr)
library(mlogit)
library(MASS)
library(foreign)
library(stargazer)
library(lmtest)
library(arm)
library(Hmisc)
library(corrplot)
library(AER)
library(cowplot)
library(PerformanceAnalytics)
library(Zelig)
library(car)
library(lmtest)
library(psych)
library(magicfor)
library(foreach)
library(iterators)
```

#Botswana
```{r}
#Load Botswana
data <- read.csv("botswana_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & votedflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1,0,0),2), j = rep(c(0,1),4), z = c(rep(1,4),rep(0,4)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:4,1],results[5:8,1]))
colnames(results) <- c("voted","nvoted")

#Total and subtotal individuals w & w/o disabilities
iwdtot <- c(sum(results[1:2,1]), sum(results[1:2,2]))
iwodtot <- c(sum(results[3:4,1]), sum(results[3:4,2]))
total <- c(sum(results$voted),sum(results$nvoted))

results <- rbind(results, iwdtot, iwodtot, total)

rm(iwdtot, iwodtot, total)

#Generate percentages
results$vpercent <- results$voted/sum_row(results$voted,results$nvoted)
results$nvpercent <- results$nvoted/sum_row(results$voted,results$nvoted)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder

nvci <- foreach(i = results[,"nvpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nvci) <- c("nvlower95", "nvupper95")

vci <- foreach(i = results[,"vpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(vci) <- c("vlower95", "vupper95")

results <- cbind(results,vci,nvci)

results <- results[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Total and for disabilities
totalchi <- chisq.test(results[1:4,1:3], correct = FALSE)
dischi <- chisq.test(results[5:6,1:3], correct = FALSE)

#Function for Chi Square for gender - can be repurposed for any combination of observations needing to be summed
chisqr2 <- function(x,y,z,t,q) {
  a <- colSums(results[c(x,y),q])
  s <- colSums(results[c(z,t),q])
  d <- rbind(a,s)
  df <- chisq.test(d, correct = FALSE)
  return(df)
  rm(a,s,d)
}
genderchi <- chisqr2(1,3,2,4,1:3)

chitest <- function(x, y) {
  chisq.test(results[c(x,y),1:2], correct = FALSE)
}

x <- combn(1:4,2)

chiresults <- foreach(i = x[1,], j = x[2,], .combine = 'rbind') %do% {
  chitest(i,j)$p.value
}
```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","mwod","wwod","iwdtot","iwodtot","total")

results$grouptot <- rowSums(results[,1:2])

results <- results[c(9,10,1:8)]

botresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
botchi <- rbind(chiresults,dischi$p.value,genderchi$p.value,totalchi$p.value)
colnames(botchi) <- c("P-Values")
comparison <- c("MwD vs WwD", "MwD vs MwoD","MwD vs WwoD","WwD vs MwoD","WwD vs WwoD", "MwoD vs WwoD", "wD vs woD", "Men vs Women", "All Four")
rownames(botchi) <- c(1: nrow(botchi))

botchi <- as.data.frame(cbind(botchi,comparison))
botchi <- botchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi")))

botchi$country <- c("Botswana")
botresults$country <- c("Botswana")
```

#Nepal
```{r}
#Load Nepal
data <- read.csv("nepal_household2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & votedflag == z) %>%
        dplyr::select(weight) %>%
        sum()
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1,0,0),2), j = rep(c(0,1),4), z = c(rep(1,4),rep(0,4)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:4,1],results[5:8,1]))
colnames(results) <- c("voted","nvoted")

#Total and subtotal individuals w & w/o disabilities
iwdtot <- c(sum(results[1:2,1]), sum(results[1:2,2]))
iwodtot <- c(sum(results[3:4,1]), sum(results[3:4,2]))
total <- c(sum(results$voted),sum(results$nvoted))

results <- rbind(results, iwdtot, iwodtot, total)

rm(iwdtot, iwodtot, total)

#Generate percentages
results$vpercent <- results$voted/sum_row(results$voted,results$nvoted)
results$nvpercent <- results$nvoted/sum_row(results$voted,results$nvoted)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder

nvci <- foreach(i = results[,"nvpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nvci) <- c("nvlower95", "nvupper95")

vci <- foreach(i = results[,"vpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(vci) <- c("vlower95", "vupper95")

results <- cbind(results,vci,nvci)

results <- results[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Total and for disabilities
totalchi <- chisq.test(results[1:4,1:3], correct = FALSE)
dischi <- chisq.test(results[5:6,1:3], correct = FALSE)

#Function for Chi Square for gender - can be repurposed for any combination of observations needing to be summed
chisqr2 <- function(x,y,z,t,q) {
  a <- colSums(results[c(x,y),q])
  s <- colSums(results[c(z,t),q])
  d <- rbind(a,s)
  df <- chisq.test(d, correct = FALSE)
  return(df)
  rm(a,s,d)
}
genderchi <- chisqr2(1,3,2,4,1:3)

chitest <- function(x, y) {
  chisq.test(results[c(x,y),1:2], correct = FALSE)
}

x <- combn(1:4,2)

chiresults <- foreach(i = x[1,], j = x[2,], .combine = 'rbind') %do% {
  chitest(i,j)$p.value
}
```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","mwod","wwod","iwdtot","iwodtot","total")

results$grouptot <- rowSums(results[,1:2])

results <- results[c(9,10,1:8)]

nepalresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
nepalchi <- rbind(chiresults,dischi$p.value,genderchi$p.value,totalchi$p.value)
colnames(nepalchi) <- c("P-Values")
comparison <- c("MwD vs WwD", "MwD vs MwoD","MwD vs WwoD","WwD vs MwoD","WwD vs WwoD", "MwoD vs WwoD", "wD vs woD", "Men vs Women", "All Four")
rownames(nepalchi) <- c(1: nrow(nepalchi))

nepalchi <- as.data.frame(cbind(nepalchi,comparison))
nepalchi <- nepalchi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalresults","nepalchi")))

nepalchi$country <- c("Nepal")
nepalresults$country <- c("Nepal")
```

#Swaziland
```{r}
#Load Swaziland
data <- read.csv("swazi_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & votedflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1,0,0),2), j = rep(c(0,1),4), z = c(rep(1,4),rep(0,4)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:4,1],results[5:8,1]))
colnames(results) <- c("voted","nvoted")

#Total and subtotal individuals w & w/o disabilities
iwdtot <- c(sum(results[1:2,1]), sum(results[1:2,2]))
iwodtot <- c(sum(results[3:4,1]), sum(results[3:4,2]))
total <- c(sum(results$voted),sum(results$nvoted))

results <- rbind(results, iwdtot, iwodtot, total)

rm(iwdtot, iwodtot, total)

#Generate percentages
results$vpercent <- results$voted/sum_row(results$voted,results$nvoted)
results$nvpercent <- results$nvoted/sum_row(results$voted,results$nvoted)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder

nvci <- foreach(i = results[,"nvpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nvci) <- c("nvlower95", "nvupper95")

vci <- foreach(i = results[,"vpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(vci) <- c("vlower95", "vupper95")

results <- cbind(results,vci,nvci)

results <- results[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Total and for disabilities
totalchi <- chisq.test(results[1:4,1:3], correct = FALSE)
dischi <- chisq.test(results[5:6,1:3], correct = FALSE)

#Function for Chi Square for gender - can be repurposed for any combination of observations needing to be summed
chisqr2 <- function(x,y,z,t,q) {
  a <- colSums(results[c(x,y),q])
  s <- colSums(results[c(z,t),q])
  d <- rbind(a,s)
  df <- chisq.test(d, correct = FALSE)
  return(df)
  rm(a,s,d)
}
genderchi <- chisqr2(1,3,2,4,1:3)

chitest <- function(x, y) {
  chisq.test(results[c(x,y),1:2], correct = FALSE)
}

x <- combn(1:4,2)

chiresults <- foreach(i = x[1,], j = x[2,], .combine = 'rbind') %do% {
  chitest(i,j)$p.value
}
```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","mwod","wwod","iwdtot","iwodtot","total")

results$grouptot <- rowSums(results[,1:2])

results <- results[c(9,10,1:8)]

swaziresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
swazichi <- rbind(chiresults,dischi$p.value,genderchi$p.value,totalchi$p.value)
colnames(swazichi) <- c("P-Values")
comparison <- c("MwD vs WwD", "MwD vs MwoD","MwD vs WwoD","WwD vs MwoD","WwD vs WwoD", "MwoD vs WwoD", "wD vs woD", "Men vs Women", "All Four")
rownames(swazichi) <- c(1: nrow(swazichi))

swazichi <- as.data.frame(cbind(swazichi,comparison))
swazichi <- swazichi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults")))

swazichi$country <- c("Swaziland")
swaziresults$country <- c("Swaziland")
```

#Lesotho
```{r}
#Load Lesotho
data <- read.csv("lesotho_disabilities2.csv")
```

```{r}
#Generate Baseline Data set

#Function to calculate observations
count_matches <- function(x, y, z) {
  data%>%
        filter(disflag == x & sexflag == y & votedflag == z) %>%
        dplyr::select(disflag) %>%
        summarise(length(disflag))
}

#Record observations of each combination
results <- foreach(i = rep(c(1,1,0,0),2), j = rep(c(0,1),4), z = c(rep(1,4),rep(0,4)), .combine = 'rbind')%do% {
  count_matches(i,j,z)
}

results <- as.data.frame(cbind(results[1:4,1],results[5:8,1]))
colnames(results) <- c("voted","nvoted")

#Total and subtotal individuals w & w/o disabilities
iwdtot <- c(sum(results[1:2,1]), sum(results[1:2,2]))
iwodtot <- c(sum(results[3:4,1]), sum(results[3:4,2]))
total <- c(sum(results$voted),sum(results$nvoted))

results <- rbind(results, iwdtot, iwodtot, total)

rm(iwdtot, iwodtot, total)

#Generate percentages
results$vpercent <- results$voted/sum_row(results$voted,results$nvoted)
results$nvpercent <- results$nvoted/sum_row(results$voted,results$nvoted)
```

```{r}
#Generate Confidence intervals
#Define functions for upper, lower, and both
u95conint <- function(x,y,z) {
  x + y * sqrt((x*(1-x))/z)
}

l95conint <- function(x,y,z) {
  x - y * sqrt((x*(1-x))/z)
}

conint <- function(x, y, z) {
   u <- x + y * sqrt((x*(1-x))/z)
   l <- x - y * sqrt((x*(1-x))/z)
   ci <- cbind(l,u)
   return(ci)
}

#Generate the results from above functions, bind to original results and reorder

nvci <- foreach(i = results[,"nvpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(nvci) <- c("nvlower95", "nvupper95")

vci <- foreach(i = results[,"vpercent"], j = rep(1.96, nrow(results)), k = rowSums(results[,1:3]), .combine = 'rbind') %do% {
  conint(i,j,k)
}
colnames(vci) <- c("vlower95", "vupper95")

results <- cbind(results,vci,nvci)

results <- results[c(1:2,5,3,6,7,4,8)]
```

```{r, error = FALSE, warning = FALSE}
#Chi Square Tests for Differences

#Chi Square for Total and for disabilities
totalchi <- chisq.test(results[1:4,1:3], correct = FALSE)
dischi <- chisq.test(results[5:6,1:3], correct = FALSE)

#Function for Chi Square for gender - can be repurposed for any combination of observations needing to be summed
chisqr2 <- function(x,y,z,t,q) {
  a <- colSums(results[c(x,y),q])
  s <- colSums(results[c(z,t),q])
  d <- rbind(a,s)
  df <- chisq.test(d, correct = FALSE)
  return(df)
  rm(a,s,d)
}
genderchi <- chisqr2(1,3,2,4,1:3)

chitest <- function(x, y) {
  chisq.test(results[c(x,y),1:2], correct = FALSE)
}

x <- combn(1:4,2)

chiresults <- foreach(i = x[1,], j = x[2,], .combine = 'rbind') %do% {
  chitest(i,j)$p.value
}
```

```{r}
#Add a Group Name and Total, Reorder Variables, Save Country Results

results$group <- c("mwd","wwd","mwod","wwod","iwdtot","iwodtot","total")

results$grouptot <- rowSums(results[,1:2])

results <- results[c(9,10,1:8)]

lesresults <- results

#Add a Group Name, Reorder Variables, Save Country Chi
leschi <- rbind(chiresults,dischi$p.value,genderchi$p.value,totalchi$p.value)
colnames(leschi) <- c("P-Values")
comparison <- c("MwD vs WwD", "MwD vs MwoD","MwD vs WwoD","WwD vs MwoD","WwD vs WwoD", "MwoD vs WwoD", "wD vs woD", "Men vs Women", "All Four")
rownames(leschi) <- c(1: nrow(leschi))

leschi <- as.data.frame(cbind(leschi,comparison))
leschi <- leschi[c(2,1)]

#Remove Extraneous Information to move to next country
rm(list = setdiff(ls(),c("botresults", "botchi","nepalchi","nepalresults","swazichi","swaziresults", "lesresults","leschi")))

leschi$country <- c("Lesotho")
lesresults$country <- c("Lesotho")
```

#Plots
```{r}
#Combine the 3 Data Sets

totalresults <- rbind(botresults, nepalresults, swaziresults, lesresults)

totalresults <- totalresults[c(11,1:10)]

rownames(totalresults) <- c(1:nrow(totalresults))

write.table(totalresults, file = "vote_analysis.csv", sep = ",", row.names = F)

#Combine the 3 Chi Sets

totalchi <- rbind(botchi, nepalchi, swazichi, leschi)

totalchi <- totalchi[c(3,1,2)]

rownames(totalchi) <- c(1:nrow(totalchi))

write.table(totalchi, file = "vote_chi.csv", sep = ",", row.names = F)
```

```{r}
#Plot the results

totalresults$group <- as.factor(totalresults$group)

print(levels(totalresults$group))

totalresults$group <- factor(totalresults$group, levels(totalresults$group)[c(3,6,4,7,1,2,5)])

ggplot(data = totalresults, aes(x = group, y = nvpercent, group = country)) +
  geom_point(aes(color = country)) +
  geom_errorbar(ymin = totalresults$nvlower95, ymax = totalresults$nvupper95)+
  labs(title = "Rate of Self Reported\n nvoted Total Health by Group", x = "Groupings of Individuals", y = "Percent Reporting\n nvoted Health", color = "Country") +
  coord_cartesian(ylim = c(0,.6)) +
  scale_y_continuous(breaks = seq(0,.6,.1), labels = scales::percent)
```